batch_size: 8
clients_per_round: 3
data_dir: ./data/cnndm
eval_steps: 500
learning_rate: 5e-5
length_penalty: 2.0
local_epochs: 1
logging_steps: 100
max_grad_norm: 1.0
max_source_length: 1024
max_target_length: 142
max_test_samples: null
max_train_samples: null
max_val_samples: null
model_name: facebook/bart-large-cnn
model_save_path: ./experiment_results/clients_7/saved_models
no_repeat_ngram_size: 3
num_beams: 4
num_clients: 7
num_rounds: 5
output_dir: ./experiment_results/clients_7
save_steps: 1000
seed: 42
test_split: test
train_split: train
use_wandb: true
val_split: validation
warmup_steps: 500
weight_decay: 0.01
